/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.wellnesswayfinder;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author watss
 */
public class WeightFrame extends javax.swing.JFrame {

    /**
     * Creates new form WeightFrame
     */
    
    public WeightFrame() {
        initComponents();
    }
    //close window method
    public void close(){
            WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
            Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldInputWeight = new javax.swing.JTextField();
        jButtonWeightNext = new javax.swing.JButton();
        jButtonWeightBack = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\watss\\Documents\\NetBeansProjects\\WellnessWayFinder\\src\\main\\java\\image\\GenderPanel1.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\watss\\Documents\\NetBeansProjects\\WellnessWayFinder\\src\\main\\java\\image\\WeightPanel.png")); // NOI18N
        jPanel1.add(jLabel2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 150));

        jPanel2.setBackground(new java.awt.Color(25, 25, 31));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jProgressBar1.setBackground(new java.awt.Color(217, 217, 217));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(520, 16));
        jPanel2.add(jProgressBar1);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 600, -1));

        jPanel3.setPreferredSize(new java.awt.Dimension(600, 290));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(75, 75, 75));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("WEIGHT (kg): ");

        jTextFieldInputWeight.setBackground(new java.awt.Color(217, 217, 217));
        jTextFieldInputWeight.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        jTextFieldInputWeight.setForeground(new java.awt.Color(75, 75, 75));
        jTextFieldInputWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldInputWeight.setText("Input Weight");
        jTextFieldInputWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(79, 79, 79), 3));
        jTextFieldInputWeight.setPreferredSize(new java.awt.Dimension(135, 33));
        jTextFieldInputWeight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldInputWeightMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldInputWeightMouseExited(evt);
            }
        });
        jTextFieldInputWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInputWeightActionPerformed(evt);
            }
        });

        jButtonWeightNext.setIcon(new javax.swing.ImageIcon("C:\\Users\\watss\\Documents\\NetBeansProjects\\WellnessWayFinder\\src\\main\\java\\image\\NextButton.png")); // NOI18N
        jButtonWeightNext.setBorder(null);
        jButtonWeightNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWeightNextActionPerformed(evt);
            }
        });

        jButtonWeightBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\watss\\Documents\\NetBeansProjects\\WellnessWayFinder\\src\\main\\java\\image\\BackButton.png")); // NOI18N
        jButtonWeightBack.setBorder(null);
        jButtonWeightBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWeightBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonWeightBack, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonWeightNext, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jTextFieldInputWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldInputWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonWeightNext, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonWeightBack, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        setSize(new java.awt.Dimension(614, 457));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldInputWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInputWeightActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldInputWeightActionPerformed

    private void jTextFieldInputWeightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldInputWeightMouseClicked
        this.jTextFieldInputWeight.setText("");
    }//GEN-LAST:event_jTextFieldInputWeightMouseClicked

    private void jButtonWeightNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWeightNextActionPerformed
        // TODO add your handling code here:
        close();
        HeightFrame heightFrame = new HeightFrame();
        heightFrame.setVisible(true);
    }//GEN-LAST:event_jButtonWeightNextActionPerformed

    private void jButtonWeightBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWeightBackActionPerformed
        
        close();
        GenderFrame genderFrame = new GenderFrame();
        genderFrame.setVisible(true);
    }//GEN-LAST:event_jButtonWeightBackActionPerformed

    private void jTextFieldInputWeightMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldInputWeightMouseExited
        // when the mouse point exited the String "Input Weight" appears again
        this.jTextFieldInputWeight.setText("Input Weight");
    }//GEN-LAST:event_jTextFieldInputWeightMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeightFrame().setVisible(true);
            }
        });
    }

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonWeightBack;
    private javax.swing.JButton jButtonWeightNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField jTextFieldInputWeight;
    // End of variables declaration//GEN-END:variables
}
